# Generated by Django 4.1.11 on 2023-12-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_attendancerecord_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='date',
        ),
    ]
