# Generated by Django 4.1.11 on 2023-12-04 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_attendancerecord_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
